FROM alpine:3.22

RUN apk update && \
    apk add --no-cache \
        lighttpd \
	lighttpd-mod_auth \
        php83 \
        php83-cgi \
        python3 && \
    # Clean up apk cache
    rm -rf /var/cache/apk/*

EXPOSE 8080

CMD ["lighttpd", "-D", "-f", "/etc/lighttpd/lighttpd.conf"]
