global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100', '192.168.122.3:9100', '192.168.122.4:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8098']
        
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
